Repository consenlabs/token-profile, pull requests merged in 2018-12, with the labels that each got.

#3217 添加grak，请合并一下
  erc20/0xFfD6F608907914975b3713c89211faf2c70EcE05.json
  images/0xFfD6F608907914975b3713c89211faf2c70EcE05.png
Labels: no transaction

#3389 add cfly token profile
  erc20/0x5b76164b61cc7ab42fcfebc16d0ef6411839d5bd.json
  images/0x5b76164b61cc7ab42fcfebc16d0ef6411839d5bd.png
Labels: unqualified logo

#3377 NODE
  erc20/0x0De059Aa5dd17427B58145782143c4e3D2dDa6aB.json
  images/0x0De059Aa5dd17427B58145782143c4e3D2dDa6aB.png
Labels: invalid

#3407 add LE Token information and logo
  erc20/0x4b353a668f90025337e7f1fcd4202c41f50a22df.json
  images/0x4b353a668f90025337e7f1fcd4202c41f50a22df.png
Labels: help_wanted

#3458 dd
  erc20/0xc2be193f581f129ace32d2fe949d100dc09c2a05.json
  images/0xc2be193f581f129ace32d2fe949d100dc09c2a05.png
Labels: project_info_unprovided

#3432 Add ABB Token
  erc20/0xbde6ff7ff944aa8ef554410572dfee184d25302a.json
  images/0xbde6ff7ff944aa8ef554410572dfee184d25302a.png
Labels: unqualified_logo
