Repository consenlabs/token-profile, pull requests merged in 2019-01, with the labels that each got.

#3391 Add Crypto.com Chain (CRO) to ERC20 token profile
  erc20/0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b.json
  images/0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b.png
Labels: unqualified_logo

#3452 0xE40f4f1B89Ab5CDfB57e8375AEec280A3952A32d
  erc20/0xE40f4f1B89Ab5CDfB57e8375AEec280A3952A32d.json
  images/0xE40f4f1B89Ab5CDfB57e8375AEec280A3952A32d.png
Labels: unqualified_logo

#3468 Add token DEBB
  erc20/0x6B9464F9B2348ec4fBc69803B07e2BB52AFAd6ac.json
  images/0x6B9464F9B2348ec4fBc69803B07e2BB52AFAd6ac.png
Labels: unqualified_logo

#3470 Add BHT token
  erc20/0xFC29B6e626B67776675FfF55d5BC0452d042F434.json
  images/0xFC29B6e626B67776675FfF55d5BC0452d042F434.png
Labels: No checksum

#3494 Add ETB-Token token
  erc20/0x214bD5A172468c2AcCe50992e8ce5a2a40CB6b16.json
  images/0x214bD5A172468c2AcCe50992e8ce5a2a40CB6b16.png
Labels: no_transaction

#3518 Add MANGO token
  eos-token/MANGO@mangotokenll.json
  images/MANGO@mangotokenll.png
Labels: unqualified_logo

#3507 Mtoken
  erc20/0xF8C8c211e976CF65eC8f01B7c70021a3b8bf5575.json
  images/0xF8C8c211e976CF65eC8f01B7c70021a3b8bf5575.png
Labels: No checksum

#3511 ADD GBC token
  erc20/0x02639FC688DF086f18Ce5E7f0F014bc74DE0229b.json
  images/0x02639FC688DF086f18Ce5E7f0F014bc74DE0229b.png
Labels: No checksum, unqualified_logo

#3567 CPT new contract cupidchain (CPC)
  erc20/0xDAE1Cac6fB6174c4712229f18ae6797B2C3401d4.json
  images/0xDAE1Cac6fB6174c4712229f18ae6797B2C3401d4.png
Labels: project_info_unprovided
