Repository consenlabs/token-profile, pull requests merged in 2019-04, with the labels that each got.

#3875 Add BEES token
  eos-token/BEES@beesgamecont.json
  images/BEES@beesgamecont.png
Labels: project_info_unprovided

#3866 Tool token
  erc20/0x84CD9d75Af2786d20504FB50bDE9F2c2339390B3.json
  images/0x84CD9d75Af2786d20504FB50bDE9F2c2339390B3.png
Labels: unqualified_logo

#3935 Add Ultrain token
  erc20/0x8716Fc5Da009D3A208f0178b637a50F4ef42400F.json
  images/0x8716Fc5Da009D3A208f0178b637a50F4ef42400F.png
Labels: unqualified_logo

#3932 Add BIDA token
  erc20/0xFbcFCf87F2659ad2e18c4B907198B4a20E78baBB.json
  images/0xFbcFCf87F2659ad2e18c4B907198B4a20E78baBB.png
Labels: need to verified

#3986 token SP
  erc20/0x33aD8CCD192c2B1782b0d3E557e32a54771E16F1.json
  images/0x33aD8CCD192c2B1782b0d3E557e32a54771E16F1.png
Labels: need to verified

#3962 Add BCV token
  erc20/0x1014613E2B3CBc4d575054D4982E580d9b99d7B1.json
  images/0x1014613E2B3CBc4d575054D4982E580d9b99d7B1.png
Labels: auto_check_failed, need to verified

#4069 Add UZT0 token
  erc20/0xfa1004e9c0063E59DBf965B9490f3153B87Fb45f.json
  images/0xfa1004e9c0063E59DBf965B9490f3153B87Fb45f.png
Labels: need to verified, unqualified_logo
