Repository consenlabs/token-profile, pull requests merged in 2019-05, with the labels that each got.

#4005 update LBA info
  erc20/0xfe5F141Bf94fE84bC28deD0AB966c16B17490657.json
  erc20/0xfe5f141bf94fe84bc28ded0ab966c16b17490657.json
  images/0xfe5F141Bf94fE84bC28deD0AB966c16B17490657.png
  images/0xfe5f141bf94fe84bc28ded0ab966c16b17490657.png
Labels: no_checksum

#4026 Add Yoo token
  erc20/0xC7596f3FC97AE603e1D7FfA61e6eFb7B6a59Bed2.json
  images/0xC7596f3FC97AE603e1D7FfA61e6eFb7B6a59Bed2.png
Labels: file_change_unnecessary

#4092 Add GQ
  erc20/0x2Dae7Da77d3Ea6F83e1Ea81ca2604C30d0B1cB00.json
  images/0x2Dae7Da77d3Ea6F83e1Ea81ca2604C30d0B1cB00.png
Labels: need to verified

#4091 Add hds token
  erc20/0xcAFE27178308351a12ffFffDeb161d9d730DA082.json
  images/0xcAFE27178308351a12ffFffDeb161d9d730DA082.png
Labels: need to verified

#4103 ADD-ISAS-TOKEN
  erc20/0xB7458EddbB126d82Ef563d1b9BFAcFD30C67291D.json
  images/0xB7458EddbB126d82Ef563d1b9BFAcFD30C67291D.png
Labels: need to verified

#4119 Add SEAL token
  erc20/0x07bf5F95851Ef2b2996F192569e406A6FeA2a95a.json
  images/0x07bf5F95851Ef2b2996F192569e406A6FeA2a95a.png
Labels: unqualified_logo

#3995 Added AMLT
  erc20/0xCA0e7269600d353F70b14Ad118A49575455C0f2f.json
  images/0xCA0e7269600d353F70b14Ad118A49575455C0f2f.png
Labels: need to verified

#4106 add HGT token
  erc20/0xc0f3AA07DFd62a538bb370bD8A2A8597EF491C74.json
  images/0xc0f3AA07DFd62a538bb370bD8A2A8597EF491C74.png
Labels: need to verified
