Repository consenlabs/token-profile, pull requests merged in 2019-10, with the labels that each got.

#5060 Dx token
  erc20/0x973e52691176d36453868D9d86572788d27041A9.json
  images/0x973e52691176d36453868D9d86572788d27041A9.png
Labels: no_checksum

#5062 Add CHE token
  erc20/0x72978B6b02A09372F86DC2549dcC9A8eBEd24434.json
  images/0x72978B6b02A09372F86DC2549dcC9A8eBEd24434.png
Labels: unqualified_logo

#5063 Add XLDZ token
  erc20/0x2F5cDC81a729B750F3B733Cb95660E788441c71E.json
  images/0x2F5cDC81a729B750F3B733Cb95660E788441c71E.png
Labels: need to verified

#5049 Add CCC token and delist CCCX token
  erc20/0xbF59e6fe2Bc4eE8D303E493390b4aacab16fcc91.json
  images/0xbF59e6fe2Bc4eE8D303E493390b4aacab16fcc91.png
Labels: need to verified, unqualified_logo
