Repository consenlabs/token-profile, pull requests merged in 2019-02, with the labels that each got.

#3607 Add BLC token
  erc20/0x1C5b21eF69AF0F63950843E26c4477975B753fce.json
  images/0x1C5b21eF69AF0F63950843E26c4477975B753fce.png
Labels: no_checksum

#3640 Carbon usd token
  eos-token/CUSD@stablecarbon.json
  erc20/0x1410d4eC3D276C0eBbf16ccBE88A4383aE734eD0.json
  images/0x1410d4eC3D276C0eBbf16ccBE88A4383aE734eD0.png
  images/CUSD@stablecarbon.png
Labels: auto_check_failed

#3657 add FAcoin
  erc20/0xc5cdBab998288D4BA948847d982A32Bce77Ab591.json
  images/0xc5cdBab998288D4BA948847d982A32Bce77Ab591.png
Labels: project_info_unprovided

#3694 Add INVE token
  eos-token/INVE@intervalue11.json
  images/INVE@intervalue11.png
Labels: auto_check_failed
