Repository consenlabs/token-profile, pull requests merged in 2019-09, with the labels that each got.

#4810 vic-token added
  erc20/0xE0aE7e421FD9F68382b112cF8bE74033534cD58e.json
  images/0xE0aE7e421FD9F68382b112cF8bE74033534cD58e.png
Labels: need to verified, no_checksum

#4789 Add BQQQ token
  erc20/0x1B80eeeaDcC590f305945BCc258cFa770Bbe1890.json
  images/0x1B80eeeaDcC590f305945BCc258cFa770Bbe1890.png
Labels: need to verified

#4793 Add EON token
  erc20/0x4CB10F4df4BF4F64D4797d00D468181EF731Be9A.json
  images/0x4CB10F4df4BF4F64D4797d00D468181EF731Be9A.png
Labels: need to verified

#4832 Add Dbank token
  erc20/0x42a952Ac23d020610355Cf425d0dfa58295287BE.json
  images/0x42a952Ac23d020610355Cf425d0dfa58295287BE.png
Labels: need to verified

#4817 TDC-token
  erc20/0x763308a9bbFaa76790BfcBC9b160e8FA447b2D82.json
  images/0x763308a9bbFaa76790BfcBC9b160e8FA447b2D82.png
Labels: invalid, need to verified

#4856 ERC20 Token DCS
  erc20/0x53d47C83fCB0af1BB307736d288c75307A6abcD5.json
  images/0x53d47C83fCB0af1BB307736d288c75307A6abcD5.png
Labels: need to verified

#4794 Add POW & POWX tokens
  eos-token/POW@powhcontract.json
  eos-token/POWX@powxtokenpow.json
  images/POW@powhcontract.png
  images/POWX@powxtokenpow.png
Labels: need to verified, project_info_unprovided

#4694 提交BJS
  erc20/0x65D2a81c2Df8ff655030300b8efc9Cd8Aa222866.json
  images/0x65D2a81c2Df8ff655030300b8efc9Cd8Aa222866.png
Labels: need to verified

#4917 Add LIN token
  erc20/0x65C742D3BEA980155d67C0FE421dBDeEAa1c9083.json
  images/0x65C742D3BEA980155d67C0FE421dBDeEAa1c9083.png
Labels: no_checksum

#4933 Add qc token
  erc20/0xE74B35425fE7E33EA190b149805baF31139a8290.json
  images/0xE74B35425fE7E33EA190b149805baF31139a8290.png
Labels: invalid
