Repository consenlabs/token-profile, pull requests merged in 2019-08, with the labels that each got.

#4725 Add UNI token
  erc20/0x2730d6FdC86C95a74253BefFaA8306B40feDecbb.json
  images/0x2730d6FdC86C95a74253BefFaA8306B40feDecbb.png
Labels: unqualified_logo

#4779 Add THP token
  erc20/0xAeC39406348bEcc28aa008b70FEf6063a36CE10f.json
  images/0xAeC39406348bEcc28aa008b70FEf6063a36CE10f.png
Labels: auto_check_failed

#4719 Added TAL Token
  erc20/0x375A08cE3a460F20BbaFd282Be1E3579a2c31F41.json
  images/0x375A08cE3a460F20BbaFd282Be1E3579a2c31F41.png
Labels: need to verified
