Repository consenlabs/token-profile, pull requests merged in 2021-05, with the labels that each got.

#6928 Add Ainu token
  erc20/0xa52817Aba4FA2533E6bE9f4e82C47de738649D09.json
  images/0xa52817Aba4FA2533E6bE9f4e82C47de738649D09.png
Labels: no_checksum

#6935 add yfs token
  erc20/0x92d984Ff5593fcc209Adb525Adef90D119EB0D9d.json
  images/0x92d984Ff5593fcc209Adb525Adef90D119EB0D9d.png
Labels: need to verified

#6949 Add sts token
  erc20/0x33afDedD864fa9d438D7E65d215C10A8eB141c62.json
  images/0x33afDedD864fa9d438D7E65d215C10A8eB141c62.png
Labels: need to verified

#6960 Add AOM token
  erc20/0x060924FB947e37EEE230d0B1A71D9618aEc269fC.json
  images/0x060924FB947e37EEE230d0B1A71D9618aEc269fC.png
Labels: need to verified

#6957 Add BTC2x-FLI
  erc20/0x0B498ff89709d3838a063f1dFA463091F9801c2b.json
  images/0x0B498ff89709d3838a063f1dFA463091F9801c2b.png
Labels: unqualified_logo

#6926 Add SPOC token
  erc20/0x1A82E31Ce0565C2328d4c7dCc968bfBeE8BF545c.json
  images/0x1A82E31Ce0565C2328d4c7dCc968bfBeE8BF545c.png
Labels: unqualified_logo

#6929 Add APN token
  erc20/0xd4342a57eCf2Fe7ffA37c33cb8f63b1500e575E6.json
  images/0xd4342a57eCf2Fe7ffA37c33cb8f63b1500e575E6.png
Labels: no_checksum

#6966 add goofy token
  erc20/0x6466165eF085C4b5Bc9C978397b128A85d12c184.json
  images/0x6466165eF085C4b5Bc9C978397b128A85d12c184.png
Labels: auto_check_failed

#6987 Add O3 Swap Token
  erc20/0xEe9801669C6138E84bD50dEB500827b776777d28.json
  images/0xEe9801669C6138E84bD50dEB500827b776777d28.png
Labels: need to verified

#6978 Add ZKTR token
  erc20/0xC53d46Fd66edeB5d6F36e53BA22eee4647e2Cdb2.json
  images/0xC53d46Fd66edeB5d6F36e53BA22eee4647e2Cdb2.png
Labels: need to verified
