Repository consenlabs/token-profile, pull requests merged in 2021-06, with the labels that each got.

#6990 add hgc token
  erc20/0x374C960857c9A9EcD39b47FCC420277271e46568.json
  images/0x374C960857c9A9EcD39b47FCC420277271e46568.png
Labels: need to verified

#7007 Add HTC token
  erc20/0xF13948Cc56400165FBAf08e0E7A1878CdfE6E4e4.json
  images/0xF13948Cc56400165FBAf08e0E7A1878CdfE6E4e4.png
Labels: need to verified

#7009 Add cast token
  erc20/0x9CC0d089f2E062a89213580fd3Be8aaDa584F608.json
  images/0x9CC0d089f2E062a89213580fd3Be8aaDa584F608.png
Labels: unqualified_logo

#7006 Lox token
  erc20/0xc082Ef37D36c639ee514A8021E7B80f1800e4B2f.json
  images/0xc082Ef37D36c639ee514A8021E7B80f1800e4B2f.png
Labels: unqualified_logo

#7025 Add ETW token
  erc20/0x1B6dC44F2Da393E530bD3887e32c5d55c88e6079.json
  images/0x1B6dC44F2Da393E530bD3887e32c5d55c88e6079.png
Labels: no_checksum

#7018 Add BITE token
  erc20/0x4eED0fa8dE12D5a86517f214C2f11586Ba2ED88D.json
  images/0x4eED0fa8dE12D5a86517f214C2f11586Ba2ED88D.png
Labels: token_profile_unenough
