Repository consenlabs/token-profile, pull requests merged in 2021-07, with the labels that each got.

#7044 Add Fiat24 tokens (USD24, EUR24, CHF24, GBP24)
  erc20/0x4a42255E9CF5Cc3CF1189cFDF07191CEC622c86A.json
  erc20/0xDE9e855632161a4826952ca0882d0930ab24D974.json
  erc20/0xDeb88eE896Fe1a238Eab8370752ebd727587418E.json
  erc20/0xc53959900Db973d71FfC6c9787Be4Afe55811B77.json
  images/0x4a42255E9CF5Cc3CF1189cFDF07191CEC622c86A.png
  images/0xDE9e855632161a4826952ca0882d0930ab24D974.png
  images/0xDeb88eE896Fe1a238Eab8370752ebd727587418E.png
  images/0xc53959900Db973d71FfC6c9787Be4Afe55811B77.png
Labels: need to verified

#7082 Add lec token
  erc20/0xFa30e62EEDcf80D47d42947fBCc034beeD5C09FE.json
  images/0xFa30e62EEDcf80D47d42947fBCc034beeD5C09FE.png
Labels: question

#7068 Add ETH2POS token
  erc20/0x0698DDA3c390FF92722f9EeD766D8b1727621Df9.json
  images/0x0698DDA3c390FF92722f9EeD766D8b1727621Df9.png
Labels: auto_check_failed

#7095 Add DAO token
  erc20/0xc096332CAacF00319703558988aD03eC6586e704.json
  images/0xc096332CAacF00319703558988aD03eC6586e704.png
Labels: question
